export const Message = {
    "type": "object",
    "properties": {
        "id": {
            "type": "string",
            "description": "id of the message"
        },
        "channel_id": {
            "type": "string",
            "description": "id of the channel the message was sent in"
        },
        "author": {
            "$ref": "User",
            "description": "the author of this message (not guaranteed to be a valid user, see below)"
        },
        "content": {
            "type": "string",
            "description": "contents of the message"
        },
        "timestamp": {
            "type": "string",
            "description": "when this message was sent",
            "format": "date-time"
        },
        "edited_timestamp": {
            "type": "string",
            "description": "when this message was edited (or null if never)",
            "format": "date-time"
        },
        "tts": {
            "type": "boolean",
            "description": "whether this was a TTS message"
        },
        "mention_everyone": {
            "type": "boolean",
            "description": "whether this message mentions everyone"
        },
        "mentions": {
            "$ref": "User",
            "description": "users specifically mentioned in the message"
        },
        "mention_roles": {
            "$ref": "Role",
            "description": "roles specifically mentioned in this message"
        },
        "mention_channels": {
            "$ref": "ChannelMention",
            "description": "channels specifically mentioned in this message"
        },
        "attachments": {
            "$ref": "Attachment",
            "description": "any attached files"
        },
        "embeds": {
            "$ref": "Embed",
            "description": "any embedded content"
        },
        "reactions": {
            "$ref": "Reaction",
            "description": "reactions to the message"
        },
        "nonce": {
            "type": "integer",
            "description": "used for validating a message was sent"
        },
        "pinned": {
            "type": "boolean",
            "description": "whether this message is pinned"
        },
        "webhook_id": {
            "type": "string",
            "description": "if the message is generated by a webhook, this is the webhook's id"
        },
        "type": {
            "type": "integer",
            "description": "[type of message](#DOCS_RESOURCES_CHANNEL/message-object-message-types)"
        },
        "activity": {
            "type": "unknown",
            "description": "sent with Rich Presence-related chat embeds"
        },
        "application": {
            "$ref": "Application",
            "description": "sent with Rich Presence-related chat embeds"
        },
        "application_id": {
            "type": "string",
            "description": "if the message is an [Interaction](#DOCS_INTERACTIONS_RECEIVING_AND_RESPONDING/) or application-owned webhook, this is the id of the application"
        },
        "message_reference": {
            "type": "unknown",
            "description": "data showing the source of a crosspost, channel follow add, pin, or reply message"
        },
        "flags": {
            "type": "integer",
            "description": "[message flags](#DOCS_RESOURCES_CHANNEL/message-object-message-flags) combined as a [bitfield](https://en.wikipedia.org/wiki/Bit_field)"
        },
        "referenced_message": {
            "$ref": "Message",
            "description": "the message associated with the message_reference"
        },
        "interaction": {
            "type": "unknown",
            "description": "sent if the message is a response to an [Interaction](#DOCS_INTERACTIONS_RECEIVING_AND_RESPONDING/)"
        },
        "thread": {
            "$ref": "Channel",
            "description": "the thread that was started from this message, includes [thread member](#DOCS_RESOURCES_CHANNEL/thread-member-object) object"
        },
        "components": {
            "$ref": "Component",
            "description": "sent if the message contains components like buttons, action rows, or other interactive components"
        },
        "sticker_items": {
            "$ref": "StickerItem",
            "description": "sent if the message contains stickers"
        },
        "stickers": {
            "$ref": "Sticker",
            "description": "**Deprecated** the stickers sent with the message"
        },
        "position": {
            "type": "integer",
            "description": "A generally increasing integer (there may be gaps or duplicates) that represents the approximate position of the message in a thread, it can be used to estimate the relative position of the message in a thread in company with `total_message_sent` on parent thread"
        },
        "role_subscription_data": {
            "$ref": "RoleSubscriptionData",
            "description": "data of the role subscription purchase or renewal that prompted this ROLE_SUBSCRIPTION_PURCHASE message"
        }
    },
    "required": [
        "id",
        "channel_id",
        "author",
        "content",
        "timestamp",
        "edited_timestamp",
        "tts",
        "mention_everyone",
        "mentions",
        "mention_roles",
        "mention_channels",
        "attachments",
        "embeds",
        "pinned",
        "type",
        "referenced_message",
        "components"
    ]
}